export const SUPPORTED_CROPS: string[] = [
  'Apple',
  'Bajra (Pearl Millet)',
  'Banana',
  'Barley',
  'Black Pepper',
  'Brinjal (Eggplant)',
  'Cabbage',
  'Cardamom',
  'Carrot',
  'Cauliflower',
  'Chana Dal (Chickpea)',
  'Chili',
  'Coffee',
  'Coriander',
  'Cotton',
  'Cumin',
  'Garlic',
  'Ginger',
  'Grapes',
  'Groundnut (Peanut)',
  'Guava',
  'Jowar (Sorghum)',
  'Jute',
  'Maize (Corn)',
  'Mango',
  'Masoor Dal (Red Lentil)',
  'Moong Dal (Green Gram)',
  'Mustard',
  'Okra (Lady\'s Finger)',
  'Onions',
  'Orange',
  'Pomegranate',
  'Potatoes',
  'Ragi (Finger Millet)',
  'Rice',
  'Rubber',
  'Sesame',
  'Soybean',
  'Spinach',
  'Sugarcane',
  'Sunflower',
  'Tea',
  'Tomatoes',
  'Toor Dal (Pigeon Pea)',
  'Turmeric',
  'Urad Dal (Black Gram)',
  'Wheat',
];

export const SUPPORTED_REGIONS: string[] = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const SUPPORTED_LANGUAGES: string[] = [
  'English',
  'Hindi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Bengali',
  'Marathi',
  'Gujarati',
];

const _UI_TEXTS_BASE: string[] = [
  'Region (State/District)',
  'e.g., Maharashtra or Pune',
  'Crop',
  'Get Forecast',
  'Analyzing...',
  'FarmX',
  'AI Agricultural Advisor for India',
  'No regions found. You can still enter a custom region.',
  'Latest Market Insights',
  'Refresh',
  'Could not load market trends. Please try again later.',
  'No current market trends to display.',
  'Previous trend',
  'Next trend',
  'Go to trend',
  'FarmX Recommendation',
  'Best Planting Time:',
  'Best Selling Time:',
  'Target Markets:',
  'Why This Recommendation?',
  '6-Month Forecast',
  'Expected Demand',
  'Price Range',
  'Oversupply Risk',
  'Historical Data (Last 2 Years)',
  'Month',
  'Price/Quintal (₹)',
  'Market Status',
  'FarmX Confidence:',
  'Data Sources:',
  'Analyzing Market Data...',
  'This may take a moment.',
  'Error',
  'Welcome to FarmX',
  'Your AI partner in agriculture. Select your region and a crop to receive a detailed market forecast and data-driven recommendations to maximize your yield and profits.',
  'Quick Overview',
  'Read Aloud',
  'Stop Reading',
  'AI-powered insights for modern farming.',
  'Refresh market trends',
];

// Combine base UI texts with crop names, ensuring no duplicates.
export const UI_TEXTS: string[] = [...new Set([..._UI_TEXTS_BASE, ...SUPPORTED_CROPS])];
